name: CI/CD Pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Project Dependencies
        run: npm ci
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Link local directory to vercel project and pull environment variables
        run: vercel link --token=${{ secrets.VERCEL_TOKEN }} --yes && vercel env pull .env.local --token=${{ secrets.VERCEL_TOKEN }}
      - name: Pull Vercel project settings
        run: vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}
      - name: Set NEXT_PUBLIC_TEST env variable
        run: echo "NEXT_PUBLIC_TEST=20" >> .env.local
      - name: Build with Vercel
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Install Cypress
        run: npx cypress install
      - name: Install start-server-and-test
        run: npm install start-server-and-test
      - name: Run Cypress tests
        run: npx start-server-and-test dev http://localhost:3000 cypress:run
      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
